In [ ]:
# massiv 1 
import numpy as np

n = int(input("n = "))

.
toq_sonlar = np.arange(1, 2*n, 2)

print("Dastlabki", n, "ta toq sonlar massivi:")
print(toq_sonlar)


Dastlabki 5 ta toq sonlar massivi:
[1 3 5 7 9]


In [ ]:
# massiv 2

import numpy as np

n = int(input("n ni kiriting: "))

darajalar = np.power(2, np.arange(n))

print("2 ning dastlabki", n, "ta darajalari:")
print(darajalar)


2 ning dastlabki 4 ta darajalari:
[1 2 4 8]


In [16]:
# massiv 3 
import numpy as np 
n=int(input("n="))
a=int(input("a="))
d=int(input("d="))
arifmetik_progressiya =np.arange(a,a+n*d,d)
print(arifmetik_progressiya)



[ 5 10 15 20]


In [17]:
# massiv 4 
import numpy as np

n = int(input("n="))

fibo = [0, 1]

for i in range(2, n):
    fibo.append(fibo[i-1] + fibo[i-2])

fibo = np.array(fibo[:n])

print("Dastlabki", n, "ta Fibonacci sonlari:")
print(fibo)



Dastlabki 4 ta Fibonacci sonlari:
[0 1 1 2]


In [25]:
# massiv 6 
import numpy as np 
n=int(input("n="))
a=int(input("a="))
b=int(input("=b"))

massiv=np.zeros(n,dtype=int)
massiv[0]=a
massiv[1]=1
for i in range (2,n):
    massiv[i]=np.sum(massiv[:i])
print(massiv)

[ 2  1  3  6 12 24]


In [26]:
# massiv 7 
import numpy as np 
n=int(input("n="))
massiv=np.zeros(n,dtype=int)
for i in range (n):
        massiv[i] = int(input(f"{i+1}-elementni kiriting: "))
print("Kiritilgan massiv:")
print(massiv)
teskari = massiv[::-1]
print(teskari)

Kiritilgan massiv:
[1 2 3 4]
[4 3 2 1]


In [ ]:
# massiv 8 
import numpy as np

n = int(input("n = "))


massiv = np.zeros(n, dtype=int)
for i in range(n):
    massiv[i] = int(input(f"{i+1}-elementni kiriting: "))

print("\nKiritilgan massiv:")
print(massiv)


toq_indekslar = massiv[1::2]

# Tartiblaymiz
toq_indekslar_sort = np.sort(toq_indekslar)

print("\nToq indeksli elementlar (o‘sish tartibida):")
print(toq_indekslar_sort)
print("Ularning soni:", len(toq_indekslar_sort))



Kiritilgan massiv:
[1 5 4 6 7]

jufr  indeksli elementlar (o‘sish (kamayish tartibida ):
[7 4 1]
Ularning soni: 3


In [31]:
# massiv 9
import numpy as np

n = int(input("n = "))


massiv = np.zeros(n, dtype=int)
for i in range(n):
    massiv[i] = int(input(f"{i+1}-elementni kiriting: "))

print("\nKiritilgan massiv:")
print(massiv)


juft_indekslar = massiv[0::2]

# Tartiblaymiz
juft_indekslar_sort = np.sort(juft_indekslar)[::-1]
print("\njufr  indeksli elementlar (o‘sish (kamayish tartibida ):")
print(juft_indekslar_sort)
print("Ularning soni:", len(juft_indekslar_sort))



Kiritilgan massiv:
[8 4 6 5]

jufr  indeksli elementlar (o‘sish (kamayish tartibida ):
[8 6]
Ularning soni: 2


In [33]:
# massiv 10 
import numpy as np
n=int(input("n="))
massiv = np.zeros(n, dtype=int)
for i in range(n):
    massiv[i] = int(input(f"{i+1}-elementni kiriting: "))

print("\nKiritilgan massiv:")
print(massiv)
juft_indekslar = massiv[0::2]
toq_indekslar = massiv[1::2]
juft_indekslar_sort = np.sort(juft_indekslar)[::-1]
toq_indekslar_sort = np.sort(toq_indekslar)
natija=np.concatenate(juft_indekslar_sort,toq_indekslar_sort)
print(natija)



Kiritilgan massiv:
[2 5 4 1]


TypeError: only integer scalar arrays can be converted to a scalar index

In [34]:
# massiv 11 
import numpy as np
n=int(input("n="))
k=int(input("k="))
massiv = np.zeros(n, dtype=int)
for i in range(n):
    massiv[i] = int(input(f"{i+1}"))

print("\n")
print(massiv)

natija = massiv[k::k]

print(f"\n {k} :")
print(natija)



[7 4 6 5]

 4 :
[]


In [37]:
# massiv 12 
import numpy as np

n = int(input("n= "))


massiv = np.zeros(n, dtype=int)
for i in range(n):
    massiv[i] = int(input(f"{i+1} "))

print("\n ta massiv ")
print(massiv)

natija = massiv[::2]

print("\nJuft indeksli elementlar:")
print(natija)





 ta massiv 
[4 3 5 1 0]

Juft indeksli elementlar:
[4 5 0]


In [ ]:
# massiv 13 
import numpy as np

n = int(input("n= "))

massiv = np.zeros(n, dtype=int)
for i in range(n):
    massiv[i] = int(input(f"{i+1} "))

print(massiv)

natija = massiv[1::2]

print(natija)


[5 2 2 6]
[2 6]


In [1]:
# massiv 14 
import numpy as np 
n=int(input("n="))
massiv=np.zeros(n,dtype= int)
for i in range (n):
       massiv[i] = int(input(f"{i+1}"))
print(massiv)
juft_indekslar = massiv[::2]
toq_indekslar = massiv[1::2]
natija = np.concatenate((juft_indekslar, toq_indekslar))
print(natija )

[5 6 1 3]
[5 1 6 3]


In [4]:
# massiv 15 
import numpy as np 
n=int(input("n="))
massiv=np.zeros(n,dtype= int)
for i in range (n):
       massiv[i] = int(input(f"{i+1}"))
print(massiv)
juft_indekslar = massiv[::2]
toq_indekslar = massiv[1::2]
juft_sort = np.sort(juft_indekslar)        # o‘sish tartibida
toq_sort = np.sort(toq_indekslar)[::-1]
natija = np.concatenate((juft_sort, toq_sort))
print(natija)



[2 6 5 2]
[2 5 6 2]


In [5]:
# massiv 16 
import numpy as np 
n=int(input("n="))
massiv=np.zeros(n,dtype=int)
for i in range(n):
    massiv[i]=int(input(f"{i+1}"))
print(massiv)
juft_indekslar = massiv[::2]
toq_indekslar = massiv[1::2]
toq_sort = np.sort(toq_indekslar)         # o‘sish tartibida
juft_sort = np.sort(juft_indekslar)[::-1] # kamayish tartibida
natija = np.concatenate((juft_sort, toq_sort))
print(natija)


[1 5 7 6]
[7 1 5 6]


In [7]:
# massiv 17 
import numpy as np 
n=int(input("n="))
massiv=np.zeros(n,dtype=int)
for i in range(n):
    massiv[i]=int(input(f"{i+1}"))
print(massiv)
teskari=massiv[::-1]
print(teskari)

[5 8 6 2]
[2 6 8 5]


In [10]:
# massiv 18 
import numpy as np

n = int(input("n = "))

a = []

for i in range(n):
    son = int(input(f"A[{i}] = "))
    a.append(son)

a = np.array(a)

print("\nMassiv:", a)

oxirgi = a[-1]
print("Oxirgi element:", oxirgi)

kichik = a[a < oxirgi]

if kichik.size > 0:
    print("\nOxirgi elementdan kichik bo‘lgan elementlar:", kichik)
else:
    print("0")



Massiv: [8 5 9 5 5 8 7]
Oxirgi element: 7

Oxirgi elementdan kichik bo‘lgan elementlar: [5 5 5]


In [12]:
# massiv 19 
import numpy as np

n = int(input("n = "))

a = []

for i in range(n):
    son = int(input(f"A[{i}] = "))
    a.append(son)


a = np.array(a)

print("\nMassiv:", a)

oxirgi = a[-1]
print("Oxirgi element:", oxirgi)


kichik = a[a < oxirgi]

# Shunday elementlar bo‘lmasa
if kichik.size == 0:
    print("Oxirgi elementdan kichik bo‘lgan element mavjud emas.")
else:
    eng_katta = np.max(kichik)
    indeks = np.where(a == eng_katta)[0][0]
    print(f"Oxirgi elementdan kichik bo‘lgan eng katta element: {eng_katta}")
    print(f"Indeksi: {indeks}")




Massiv: [2 6 7 9]
Oxirgi element: 9
Oxirgi elementdan kichik bo‘lgan eng katta element: 7
Indeksi: 2


In [15]:
# massiv 20
import numpy as np
n=int(input("n="))
k=int(input("k="))
l=int(input("l="))

a=[]
for _ in range(n):
    a.append(int(input("a = ")))
s = 0

for i in range(k,l+1):
    s += a[i]
print(s)


20


In [16]:
# massiv 21 
import numpy as np 
n=int(input("n="))
k=int(input("k="))
l=int(input("l="))
a=[]
for _ in range(n):
    a.append(int(input("a = ")))
s = 0

for i in range(k,l+1):
    s += a[i]
natija=(s/(l-k+1))
print(natija)

4.5


In [17]:
# massiv 22 
import numpy as np 
n=int(input("n="))
k=int(input("k="))
l=int(input("l="))
a=[]
for _ in range(n):
    a.append(int(input("a = ")))
    
s = 0

for i in range(len(a)):
    if k <= i <= l:
        continue
    else:
        s += a[i]
        
print(s)

11


In [20]:
# massiv 23 
import numpy as np 
n=int(input("n="))
k=int(input("n="))
l=int(input("l="))
a=[]
for _ in range(n):
    a.append(int(input("a = ")))
    
s = 0

for i in range(len(a)):
    if k <= i <= l:
        continue
    else:
        s += a[i]
        

natija=(s/(len(a) - (l-k+1)))
print(natija)

8.0


In [ ]:
# massiv 24 
import numpy as np 
n = int(input("n = "))

a = []

for _ in range(n):
    a.append(int(input("a = ")))
    
x = False

for i in range(3,n):
    if a[i-2] - a[i-3] == a[i] - a[i-1]:
        x = False
        
    else:
        x = True
        break
    
if x:
    print(0)
else:
    print(a[-1]-a[-2])
    